### ISSUE TITLE
ForgeRock AM/OpenAM Security Advisory #201901-04: Security Misconfiguration

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/openam#106]
## Description

TLS hostname verification is disabled by default on some services.

The severity of this issues is `Medium`.

## Reference

- [ForgeRock AM/OpenAM Security Advisory - Issue #201901-04: Security Misconfiguration](https://backstage.forgerock.com/knowledge/kb/article/a45958025)

**Comment by ogis-miyamura** [comment]
https://github.com/openam-jp/forgerock-commons/pull/11
