### ISSUE TITLE
Editing an Identity Membership environment condition should be simpler

### ISSUE THREAD

**Issue by Iwakata** [openam-jp/openam#125]
## Description

Currently, specifying an Identity membership condition requires an entry of user/group identities in the universal id format.  This is time consuming and prone to making mistakes.  

## Solution

Compared to Membership condition, editing a subject condition is much easier.  By specifying a first few words of user/group id, we can choose an intended id from a candidate list.  We should be able to do the same for the Identity Membership condition.

This will be an improvement over the resolution adopted for OPENAM-8133.

**Comment by ogis-miyamura** [comment]
The PR is fine, so the merge is complete.
