### ISSUE TITLE
ConfigureGoogleApps remove configured 'unspecified' NameID value map

### ISSUE THREAD

**Issue by idm-kiyoshi** [openam-jp/openam#228]
## Description
[ConfigureGoogleApps](https://github.com/openam-jp/openam/blob/4dcd8f2536b15d4b1fc4d345fc60c36e61b9b94c/openam-federation/OpenFM/src/main/java/com/sun/identity/workflow/ConfigureGoogleApps.java) remove configured ` unspecified ` NameID value map.

## Steps to reproduce
1. Create Hosted Identity Provider
1. Setting ` unspecified ` NameID-Format map value.  Ex.) ` urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified=mail `
1. Configure Google Apps

## Expected Results
` unspecified ` NameID-Format map value should not be changed.

## Actual Results
` unspecified ` NameID-Format map value is updated to ` urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified=uid ` .

## Enviroment
OpenAM all version

## Solution
I think one of the following.
1. remove and add NameID value map only if it ends with 'unspecified' or 'unspecified='
1. do not run updateIDPMeta

**Comment by tsujiguchitky** [comment]
`NameID Format map` is changed, it will affect the operation as SAML IdP.
Therefore, it is not possible to set up `G Suite` in operation.

> do not run updateIDPMeta

I totally agree this one.

**Comment by idm-kiyoshi** [comment]
Thanks for replying. @tsujiguchitky 
I will fix by removing updateIDPMeta.

I can't assign self to this issue. Is it necessary for self-assign?
https://github.com/openam-jp/rules/blob/master/flow/development.md#2-%E6%8B%85%E5%BD%93%E8%80%85%E3%81%AE%E3%82%A2%E3%82%B5%E3%82%A4%E3%83%B3

**Comment by tsujiguchitky** [comment]
> I will fix by removing updateIDPMeta.

Oh, thanks.

> I can't assign self to this issue. Is it necessary for self-assign?

I just assigned it.

I forgot to consider the permissions for self-assignment.
Would you like to join `openam-jp` organization members?

**Comment by idm-kiyoshi** [comment]
I'm sorry for the late reply.
I made the [Pull Request](#235), so please review.

**Comment by tsujiguchitky** [comment]
> I made the Pull Request, so please review.

Great!
I will review it ASAP.
