### ISSUE TITLE
Remove dependency on ForgeRock Maven repositories

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/openam#36]
## Description
OpenAM relies on closed ForgeRock Maven repositories. In the current situation, Maven caches are required for building OpenAM.

## Solution
Do the following items for OpenAM and dependent libraries(OpenDJ,ForgeRock Commons,etc..).

* Remove ForgeRock repository tags in pom.xml
* Change Maven groupId
* Adjust maven dependency

**Comment by ogis-miyamura** [comment]
Thank you for committing the wonderful codes.
I got success to build 12 repositories well.

I noticed the following points:

1. `openam-jp/forgerock-ui`
    - It seems that `bzip2` package is required.
    - In my opinion, along with the version specs of `JDK` and `Maven`, it is kindness to note necessary packages together.

2. `openam-jp/opendj-sdk`
    - Unit test failed in my build environment.
      ~~~
      Failed tests: 
        UtilsTestCase.testCannotWriteOnNewFile:69 expected [false] but found [true]

      Tests run: 43, Failures: 1, Errors: 0, Skipped: 0
      ~~~

    - Adding the `-DskipTests` option, build succeeded.


I will continue to check the codes.

**Comment by tsujiguchitky** [comment]
Thank you for review.

> 1. openam-jp/forgerock-ui

Sorry, I did not notice it. I think It is difficult to cover the required package because it varies depending on OS. I will describe the version of JDK and Maven in future pull requests.

> 2. openam-jp/opendj-sdk

Umm I have not seen that. Sorry to inconvenience you but please register the issue with opendj-sdk project.

**Comment by ogis-miyamura** [comment]
> > 1. openam-jp/forgerock-ui
> I think It is difficult to cover the required package because it varies depending on OS.

That is true, I realize how apparent it really is.


> I will describe the version of JDK and Maven in future pull requests.

It might be a good time for us to rewrite `openam-jp/openam/README.md` to more useful content.


> > 2. openam-jp/opendj-sdk
> 
> Umm I have not seen that. Sorry to inconvenience you but please register the issue with opendj-sdk project.

Thank you for the information.
I will try again in other build environment.
if all else fails, I'll register the issue.

**Comment by ogis-miyamura** [comment]
> In my opinion, along with the version specs of `JDK` and `Maven`, it is kindness to note necessary packages together.

I'm sorry I didn't explain it enough.
What I want to say was 'along with the version specs on https://github.com/openam-jp/openam#build-the-source-code of `JDK` and `Maven` ...'.

**Comment by tsujiguchitky** [comment]
> What I want to say was 'along with the version specs on https://github.com/openam-jp/openam#build-the-source-code of `JDK` and `Maven` ...'.

I had a misunderstanding...
Certainly it is better to add it to the README.md.
