### ISSUE TITLE
Add option to use local time zone instead of UTC in audit logging

### ISSUE THREAD

**Issue by tsujiguchitky** [openam-jp/openam#41]
## Description
The audit log timestamp is output in UTC. On the other hand, debug log timestamp is output in the local time. In addition, it seems that it is common that the logs of Web server and servlet container are output in local time.

When analyzing logs for troubleshooting, if the time zone is different, analyzing will take time. Audit logging should have a way to use local time.

## Solution
Add an item to the audit log service so that it can be switched to local time.

## References
[[OPENAM-12928] Improve audit log to have local timezone instead of standard iso time format](https://bugster.forgerock.org/jira/browse/OPENAM-12928)

**Comment by ogis-miyamura** [comment]
close #41
