### ISSUE TITLE
Is it possible to make OpenAM without the ForgeRock subscription?

### ISSUE THREAD

**Issue by hiroyuki-sato** [openam-jp/openam#8]
Hello developers.

Is it possible to make OpenAM without the ForgeRock subscription?
I got the following error during build the OpenAM.

I found this article [How do I build OpenAM 12.x and 13.x from source?](https://backstage.forgerock.com/knowledge/kb/article/a45163500)
But It seems to require subscription ID.

* OS: macOS 10.13.6
* Java: 1.8.0_121
* mvn: 3.5.4
* source: 4dcd8f2536b15d4b1fc4d345fc60c36e61b9b94c

```
mvn clean install
[INFO] Scanning for projects...
Downloading from forgerock-staging-repository: http://maven.forgerock.org/repo/releases/org/forgerock/forgerock-parent/2.0.6/forgerock-parent-2.0.6.pom
Downloading from maven.forgerock.org: http://maven.forgerock.org/repo/openam-dependencies/org/forgerock/forgerock-parent/2.0.6/forgerock-parent-2.0.6.pom
Downloading from restlet-cache: http://maven.forgerock.org/repo/maven.restlet.org/org/forgerock/forgerock-parent/2.0.6/forgerock-parent-2.0.6.pom
Downloading from oracle-repository: http://download.oracle.com/maven/org/forgerock/forgerock-parent/2.0.6/forgerock-parent-2.0.6.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/forgerock/forgerock-parent/2.0.6/forgerock-parent-2.0.6.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.forgerock.openam:openam:14.0.0-SNAPSHOT: Could not transfer artifact org.forgerock:forgerock-parent:pom:2.0.6 from/to forgerock-staging-repository (http://maven.forgerock.org/repo/releases): Not authorized , ReasonPhrase: Unauthorized. and 'parent.relativePath' points at wrong local POM @ line 50, column 13
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.forgerock.openam:openam:14.0.0-SNAPSHOT (/path/to/openam-jp/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.forgerock.openam:openam:14.0.0-SNAPSHOT: Could not transfer artifact org.forgerock:forgerock-parent:pom:2.0.6 from/to forgerock-staging-repository (http://maven.forgerock.org/repo/releases): Not authorized , ReasonPhrase: Unauthorized. and 'parent.relativePath' points at wrong local POM @ line 50, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by tsujiguchitky** [comment]
We aim for OpenAM which can be built without subscription.

However, the source code refers to the repository of ForgeRock at present. So it can not be built without Maven cache that ForgeRock published in the past.

In my opinion, we need to consider preparing our own Maven repository.

**Comment by hiroyuki-sato** [comment]
Hello, @tsujiguchitky 

Thank you for the comment.

I see.
What do you think to cooperate with [WrenAM](https://github.com/WrenSecurity/wrenam)?
I think It's good to maintain the same code for each other.

They already prepared to own the mvm repositories for ForgeRock.

**Comment by tsujiguchitky** [comment]
It is ideal to maintain same code.

However, I think that there are differences in purpose and priority and etc... , so we can not do it easily.

This repository will be maintained mainly by members of the OpenAM Consortium in Japan.
Therefore, modifications for the Japanese market such as Japanese translation will be given priority.

**Comment by hiroyuki-sato** [comment]
Hello, @tsujiguchitky 

I got it. Thank you.
